"""add workspaces table

Revision ID: 004a71ca0dc3
Revises: 8ddc2827ff00
Create Date: 2026-04-11 00:50:25.929535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004a71ca0dc3'
down_revision: Union[str, Sequence[str], None] = '8ddc2827ff00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('workspace_type', sa.Enum('public', 'private',
                                                        name='workspace_type', native_enum=False), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=255), nullable=True),
                    sa.Column('color', sa.String(length=30), nullable=False),
                    sa.Column('icon', sa.String(length=80), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces')
    # ### end Alembic commands ###
