"""add calendar tables

Revision ID: 190287be86b7
Revises: 2d9d1ae1dc58
Create Date: 2026-04-25 19:57:05.718739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190287be86b7'
down_revision: Union[str, Sequence[str], None] = '2d9d1ae1dc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
